FROM ubuntu:22.04

WORKDIR /usr/src/app

RUN apt update && apt install -y \
    curl \
    dos2unix \
    && rm -rf /var/lib/apt/lists/*

COPY script.sh .
RUN dos2unix script.sh && chmod +x script.sh

ENTRYPOINT ["./script.sh"]
