FROM node:16



WORKDIR /usr/src/app

ARG REACT_APP_BACKEND_URL
ENV REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL

COPY ./example-frontend/package*.json ./

RUN npm install

COPY ./example-frontend .
RUN npm install -g serve


RUN npm run build

CMD [ "serve", "-s", "-l", "5000", "build" ]