# Dockerfile.backend
FROM golang:1.16

WORKDIR /usr/src/app

# Kopiujemy cały projekt
COPY . .

# Kompilujemy binarkę
RUN go build -o server ./cmd/server

EXPOSE 8080

ENV PORT=8080
ENV REQUEST_ORIGIN=http://localhost:5000

CMD ["./server"]
